# Generated by Django 4.1.5 on 2023-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'So so'), (3, 'Good'), (4, 'Nice'), (5, 'Greate')], default=5),
        ),
    ]
