# Generated by Django 4.1.5 on 2023-01-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default='Неизвестно', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='movies', to='movie_app.director'),
        ),
    ]
